### ISSUE TITLE
Hernoem `StaticSection.validUntil` naar `.validThrough`

### ISSUE THREAD

**Issue by redmer** [Stichting-CROW/datastandaard-fietsparkeren#4]
Dat is namelijk expliciet _geldig t/m_, zonder ambiguïteit over _geldig tot_.

**Comment by redmer** [comment]
Voor een volgende release, aangezien dit al geïmplementeerd is op verschillende plekken?

**Comment by haverweb** [comment]
Direct aangepast in de documentatie, want in de huidige API's wordt dit veld nog niet aangeboden
